name: Call a reusable workflow

on:
  pull_request_target:

jobs:
  call-shared-master-labeler:
     uses: joebochill/test-gh-actions/.github/workflows/label-master-pr.yml@master
     secrets:
      envPAT: ${{ secrets.envPAT }}
  call-shared-labeler:
     uses: joebochill/test-gh-actions/.github/workflows/label-pr.yml@master
     secrets:
      envPAT: ${{ secrets.envPAT }}
